# Need help with configuration? Check out our complete guide:
# https://github.com/NotArb/Release/tree/main/jupiter-server#readme

[launcher]
task="jupiter-server"
jvm_args=[
    "-server",
    "-Xmx4096m",
    "-XX:+UseSerialGC"
]

[manager]
jupiter_path="" # leave empty to auto install
startup_cmd=["bash", "./startup-script.sh"] # optional, used to run a command before every start/restart.
auto_restart_minutes=10 # set to 0 or remove this line to disable auto restarts (restarts on failure will still happen)

[env]
RUST_LOG="info"
RUST_BACKTRACE="full"
HOST="127.0.0.1"
PORT="8080"
RPC_URL=""
#YELLOWSTONE_GRPC_ENDPOINT=""
#YELLOWSTONE_GRPC_X_TOKEN=""
#YELLOWSTONE_GRPC_ENABLE_PING="true"
ALLOW_CIRCULAR_ARBITRAGE="true"
MARKET_MODE="remote"
ENABLE_NEW_DEXES="true"
FILTER_MARKETS_WITH_MINTS="" # This will be ovewritten by mint filters defined below.

[[file_mints]]
enabled=true
path="mints.txt"